apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mymicroservise
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
    app.kubernetes.io/name: mymicroservise
    app.kubernetes.io/version: 1ac374df26e09cf5f0de04d92c8b923e559c1a2d
  name: mymicroservise
  namespace: default
  resourceVersion: "613534"
  uid: f96255b6-cfef-4fcb-b84e-eea77b19e341
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mymicroservise
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        gcb-build-id: 017fde38-304e-46b9-934b-84a8449f7566
        gcb-trigger-id: 4839b31f-48c2-49fa-9cdd-2caca82e2858
      creationTimestamp: null
      labels:
        app: mymicroservise
        app.kubernetes.io/managed-by: gcp-cloud-build-deploy
        app.kubernetes.io/name: mymicroservise
        app.kubernetes.io/version: 1ac374df26e09cf5f0de04d92c8b923e559c1a2d
    spec:
      containers:
      - image: gcr.io/fresh-base-350308/github.com/it19062884ruvindu/ctse-y4-microservise-2022@sha256:3ee283f9abc47cefe0b84e7147b0dc95f86f69ff11953b7c197b877057f6c38b
        imagePullPolicy: IfNotPresent
        name: ctse-y4-microservise-2022-1
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
          requests:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
        securityContext:
          capabilities:
            drop:
            - NET_RAW
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-05-16T11:42:59Z"
    lastUpdateTime: "2022-05-16T11:42:59Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-05-16T11:42:55Z"
    lastUpdateTime: "2022-05-16T12:52:37Z"
    message: ReplicaSet "mymicroservise-6b4b474977" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1